Adding excludes option
codepunkt/mongoose-patch-history pull request #63
Opened 2020-08-23 21:48 UTC by vinerich

This PR adds an `excludes: []` option which can be used to exclude certain paths of the versioned object from being versioned.

Excludes are defined as follows
```js
ExcludeSchema.plugin(patchHistory, {
  mongoose,
  name: 'excludePatches',
  excludes: ['/hidden', '/object/hiddenProperty', '/array/*/hiddenProperty'],
})
```
A exclude of `/hidden` would exclude all paths that start with `/hidden`.
For arrays I introduced the `*` symbol to specifiy a specific property inside the array to be excluded. One could ofcourse also specify a number to only exclude one array element.

#### Problems
Add the moment I have one failing test. This tests what patches are written when an object is saved initially.
At the moment I do the comparison on the `path`-property of the `json-patch`. Since `json-patch` adds only the top-level-properties when an object is added: e.g. `op:'add', path:'/object', value:'{ hiddenProperty: 'test' }'` it would take a little more effort to make the exclude work for this kind of operation.

@codepunkt Do you think this behaviour would be necessary for consistency or can we only support the `excludes` option for updates() and not for initial writing?

2020-08-26 00:03 UTC, vinerich commented
> At the moment I do the comparison on the path-property of the json-patch. Since json-patch adds only the top-level-properties when an object is added: e.g. op:'add', path:'/object', value:'{ hiddenProperty: 'test' }' it would take a little more effort to make the exclude work for this kind of operation.

I added a comparison to make exclude work for this case.

@codepunkt Please take your time to review the changes introduced. Especially in 9cf4bab. I tried to comment the method `deepRemovePath()` to full extend, but sure I didn't. If there is something unclear, feel free to ask.

I enhanced the test for most cases I could think of this evening but there are probably more to cover, which brings me to my question.
I'd really like this feature in the release, because I need it 😄. The logic is "rather" complicated and cause of that I would take it more as a beta-feature than as a fully tested one. Can't think of a case that would break it right now, but you can never be sure.. 

Would you include it in the release or do you say we need to do more test to be sure it works as intended?

Of course I'll provide documentation in the README if you choose to include it. Thanks in advance for your review.

2020-08-26 15:10 UTC, codepunkt requested changes

2020-08-26 15:12 UTC, codepunkt commented
I haven't been using mongodb or mongoose for a few years, so i can't comment on these parts. However, i think i understand the exclude use case.

I'm unsure about the `deepRemovePath` stuff because i don't understand how fast-json-patch diffentiates between nested paths and having objects as the value.

Documentation in the readme would be nice!

2020-08-26 22:58 UTC, vinerich commented on lib/index.js
> +var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.construc
I didn't do this on purpose 😄 The compiler did it. I'm not sure why. The `slice()` operation is causing it.
```js
deepRemovePath({ path: '/', value: elem }, pathToExclude.slice(i + 1))
```
I can rework this to a filter operation but I find it much cleaner this way. Your decision.

2020-08-26 23:00 UTC, vinerich commented on lib/index.js
> +        var pathArray = getArrayFromPath(op.path);
Ups, sorry for resolving this.

Sounds good!

2020-08-26 23:08 UTC, vinerich commented on lib/index.js
> +};
Which line do you mean?

This is getting rid of leading slashes only.
```java
var pathArray = path.replace(/^\//, '').split('/');
```

If you mean this statement: ` Note: '/' is returned as '[]'` I need it for the recursion of `deepRemovePath()` to work.
I'll extract it into an own function to make it clearer.

2020-08-26 23:10 UTC, vinerich commented on lib/index.js
> +    return entry === pathToCover[idx] || entry === '*' && Number.isInteger(Number(pathToCover[idx])) && Number(pathToCover[idx]) >= 0;
Will include the suggestions. Maybe I can think of a better name, getting your point tho.

2020-08-26 23:11 UTC, vinerich commented on src/index.js
> + * Checks the provided `json-patch-operation` on `pathToExclude`. This check is joins the `path` and `value` property of the `operation` and removes any hit.
Will do! And no probs.

2020-08-26 23:25 UTC, vinerich commented
Hey! At first thanks for your review, I appreciate it!
I'll try to include your suggestions and make the code more understandable. Probably should've done this one more time before pushing it, but yesterday it seems reasonably good to me.

> I'm unsure about the `deepRemovePath` stuff because i don't understand how fast-json-patch diffentiates between nested paths and having objects as the value.

As I understand it, the first `added` property is always a top-level-property, so it should always result in something like `op:'add', path:'/top-level, value:'{ ... }'`.
Every other operation results in the lower-most property path it can get, to resemble the operation.

Taking this object as a starting point: `{ top: {} }`
Adding a third-level-property `/top/second/third` gives a patch like `op:'add', path:'/top, value:'{ second: { third: { ... }}}'`.
Replacing this property after will give  `op:'replace', path:'/top/second/third, value:'{ ... }'`.
Removing this property after will give  `op:'remove', path:'/top/second/third`.

Does that clear it up a little? I'd say that these cases are covered, because at first I check if the `starting-path` is the same
```js
const deepRemovePath = (patch, pathToExclude) => {
  const patchPath = getArrayFromPath(patch.path)

  // first check if the base path of the json-patch overlaps with the path we want to exclude
  if (isPathCovered(patchPath, pathToExclude)) {
    let value = patch.value
```

and here I start to traverse at the matching index in `pathToExclude`
```js
// because the paths overlap start at patchPath.length
    // e.g.
    // patch: { path:'/object', value:{ property: 'test' } }
    // pathToExclude: '/object/property'
    // need to start at array idx 1, because value starts at idx 0
    for (let i = patchPath.length; i < pathToExclude.length - 1; i++) {
```

Documentation will take place tomorrow, I think I need some sleep.

PS.: It is hard to break down the code, and especially the thoughts I had while writing it and how I expect it to work. I hope it is understandable. Thanks again for the review!!!

2020-08-27 15:45 UTC, codepunkt commented
It's understandable, you're doing a really good job here!

2020-08-27 15:46 UTC, codepunkt commented on lib/index.js
> +var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.construc
It's fine. My fault for reviewing the compiled code.
If would set this repo up afresh today, i'd not check the compiled code in but compile before publish.

It is as it is. This one's good!

2020-08-27 15:47 UTC, codepunkt commented on lib/index.js
> +};
Was just a generic question i had when i saw this area of the code. I guess it never has trailing slashes 👍

2020-08-27 15:47 UTC, codepunkt approved these changes

2020-08-28 06:29 UTC, vinerich commented on lib/index.js
> +var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.construc
That'd would probably be the best! It's a little missleading that `/lib/index.js` is in front of `/src/index.js`.

2020-08-28 06:29 UTC, vinerich commented on lib/index.js
> +};
Ah ok, I don't think so too. Wouldn't make sense to me.

2020-08-28 06:31 UTC, vinerich commented
@codepunkt Thanks for approving!
If you are fine with the README changes feel free to merge! If you want me to include another case or specify something further let me know!
Also if any bugs encounter with this feature, summon me and I'll have a look!

2020-08-28 06:37 UTC, codepunkt commented
@vinerich I don't see any README changes yet 😀

2020-08-28 06:39 UTC, vinerich commented
@codepunkt There you go. The commit didn't work because I don't have my MongoDB on `localhost` and forgot to change it back after stash 😄

2020-08-28 08:51 UTC, codepunkt requested changes

2020-08-28 08:51 UTC, codepunkt commented on README.md
> +  Property paths that will be excluded in patches. Read more about excludes in the chapter after next. Default: `[]`
```md
Read more about excludes in the [excludes chapter of the documentation](#excludes)
```

2020-08-28 08:52 UTC, codepunkt commented on README.md
> +  Property paths that will be excluded in patches. Read more about excludes in the chapter after next. Default: `[]`
Awesome. You can link the chapter in markdown - in case the documentation grows and something goes in-between, people can jump to it directly.

2020-08-28 16:42 UTC, codepunkt approved these changes

2020-08-28 16:44 UTC, merged